// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.IdentityExample.DAL;

#nullable disable

namespace WebAPI.IdentityExample.Migrations.SchoolDb
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20230509103640_Add_Member_ClassesMemberMapping")]
    partial class Add_Member_ClassesMemberMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.IdentityExample.Model.ClassHomeworkMapping", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassId", "HomeworkId");

                    b.HasIndex("HomeworkId");

                    b.ToTable("classHomeworkMapping");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.ClassMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("classMember");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.ClassMemberMapping", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("classMemberMapping");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.Classes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsLockout")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LasTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("homeworks");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.ClassHomeworkMapping", b =>
                {
                    b.HasOne("WebAPI.IdentityExample.Model.Classes", "Class")
                        .WithMany("ClassHomeworkMappings")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.IdentityExample.Model.Homework", "homework")
                        .WithMany("ClassHomeworkMappings")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("homework");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.ClassMemberMapping", b =>
                {
                    b.HasOne("WebAPI.IdentityExample.Model.Classes", "Class")
                        .WithMany("MemberMappings")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.IdentityExample.Model.ClassMember", "User")
                        .WithMany("ClassesMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.ClassMember", b =>
                {
                    b.Navigation("ClassesMappings");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.Classes", b =>
                {
                    b.Navigation("ClassHomeworkMappings");

                    b.Navigation("MemberMappings");
                });

            modelBuilder.Entity("WebAPI.IdentityExample.Model.Homework", b =>
                {
                    b.Navigation("ClassHomeworkMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
